### ISSUE TITLE
Make this repo's relation to Boost clearer

### ISSUE THREAD

**Issue by eyalroz** [boostorg/stl_interfaces#45]
It is not entirely clear from the README.md whether this repository is part of boost, an adaptation of a part of boost for stand-alone use, or something else. Please clarify... (not here - in README.md).

**Comment by alandefreitas** [comment]
Is there a standalone version of this library?

**Comment by eyalroz** [comment]
@alandefreitas : I hope you're not asking me...

**Comment by tzlaine** [comment]
This is a boostorg subproject.
