### ISSUE TITLE
Bug: Typo in return value of adaptor::operator()

### ISSUE THREAD

**Issue by patrickroberts** [boostorg/stl_interfaces#64]
There's a typo in this class:

https://github.com/boostorg/stl_interfaces/blob/510eb431fbf64e98b6870468aa523dd4c6a6c69a/include/boost/stl_interfaces/view_adaptor.hpp#L286-L313

on this line:

https://github.com/boostorg/stl_interfaces/blob/510eb431fbf64e98b6870468aa523dd4c6a6c69a/include/boost/stl_interfaces/view_adaptor.hpp#L298

`f` should be `f_` to refer to the data member, but instead when the constexpr if statement is true and the expression isn't discarded, it is a compilation error. Effectively when `BOOST_STL_INTERFACES_USE_CONCEPTS` is set, `adaptor` can only be used with the pipe syntax (when the constexpr if is false) and cannot be invoked as the original function.

The reason it is only a compilation error when the statement isn't discarded is because the identifier `f` would only need to be resolved for the instantiation of `operator()` method template, since it could be ADL.

**Comment by tzlaine** [comment]
Thanks!  This was fixed in 0f422d58cb39, and will appear in the next Boost release.
