### ISSUE TITLE
Documentation confusing/wrong on the return type of swap of sequence_container_interface

### ISSUE THREAD

**Issue by thebrandre** [boostorg/stl_interfaces#71]
The documentation states that the retun type of the user-provided swap should be convertible to bool, see [here](https://www.boost.org/doc/libs/1_86_0/doc/html/boost_stlinterfaces/tutorial___sequence_container_interface_.html#boost_stlinterfaces.tutorial___sequence_container_interface_.container) or [here](https://github.com/boostorg/stl_interfaces/blob/develop/doc/tutorial.qbk#L653).

This would be rather unusual and seems not to be tha case. It is also inconsistent with the docs.

**Comment by tzlaine** [comment]
Yup, totally wrong.  Thanks for reporting this!
